name: Acceptance Tests

on:
  pull_request:
    types: [ready_for_review]
    branches:: [master]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  acceptance_tests:
    if: contains(github.event.pull_request.labels.*.name, 'needs-acceptance-tests')

    runs-on: ubuntu-18.04

    steps:
    - uses: softprops/turnstyle@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        same-branch-only: false

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - run: make testacc
      env:
        AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME }} 

    - uses: nick-invision/retry@v2
      if: always()
      with:
        timeout_minutes: 10
        max_attempts: 10
        command: make sweep
      env:
        AIVEN_TOKEN: ${{ secrets.AIVEN_TOKEN }}
        AIVEN_PROJECT_NAME: ${{ secrets.AIVEN_PROJECT_NAME }} 

